### ISSUE TITLE
Contiguity with Streamlit - self.token = token.strip() | AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by janduplessis883** [use-contiguity/python#2]
When Loading contiguity in [utils.py](https://github.com/janduplessis883/project-xeroconvert/blob/master/xeroconvert/utils.py) which is then imported to my [app.py](https://github.com/janduplessis883/project-xeroconvert/blob/master/xeroconvert/app.py) Streamlit Application I get an error intermittently rendering the app unusable.

In my app I am using Contiguity to verify the users email address with a verification code. Once they have completed statement extraction to csv I, send a summary report via emailed to them. Both this functionality is in utils.py.
I use streamlit secrets `st.secrets` to store my `CONTIGUITY_API` key.

When I rebuild the app it is fixed for a few hours and then I get the same error again.
I ❤️ Contiguity - such a great app, hope you can assist me.

Much appreciated.
[**Repo URL - XeroConvert**](https://github.com/janduplessis883/project-xeroconvert/tree/master)
Jan

### See below **Streamlit's Output**:

```
Traceback (most recent call last):

  File "/home/adminuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script

    exec(code, module.__dict__)

  File "/mount/src/project-xeroconvert/xeroconvert/app.py", line 9, in <module>

    from utils import *

  File "/mount/src/project-xeroconvert/xeroconvert/utils.py", line 21, in <module>

    client = contiguity.login(client_id, True)

  File "/home/adminuser/venv/lib/python3.9/site-packages/contiguity/__init__.py", line 4, in login

    return Contiguity(token, debug)

  File "/home/adminuser/venv/lib/python3.9/site-packages/contiguity/main.py", line 15, in __init__

    self.token = token.strip()

AttributeError: 'NoneType' object has no attribute 'strip'

2024-01-02 22:20:06.520 503 GET /script-health-check (10.12.7.28) 69.78ms

2024-01-02 22:20:11.458 Uncaught app exception

Traceback (most recent call last):

  File "/home/adminuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script

    exec(code, module.__dict__)

  File "/mount/src/project-xeroconvert/xeroconvert/app.py", line 9, in <module>

    from utils import *

  File "/mount/src/project-xeroconvert/xeroconvert/utils.py", line 21, in <module>

    client = contiguity.login(client_id, True)

  File "/home/adminuser/venv/lib/python3.9/site-packages/contiguity/__init__.py", line 4, in login

    return Contiguity(token, debug)

  File "/home/adminuser/venv/lib/python3.9/site-packages/contiguity/main.py", line 15, in __init__

    self.token = token.strip()

AttributeError: 'NoneType' object has no attribute 'strip'

2024-01-02 22:20:11.677 503 GET /script-health-check (10.12.7.28) 223.01ms

2024-01-02 22:20:16.434 Uncaught app exception

Traceback (most recent call last):

  File "/home/adminuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script

    exec(code, module.__dict__)

  File "/mount/src/project-xeroconvert/xeroconvert/app.py", line 9, in <module>

    from utils import *

  File "/mount/src/project-xeroconvert/xeroconvert/utils.py", line 21, in <module>

    client = contiguity.login(client_id, True)

  File "/home/adminuser/venv/lib/python3.9/site-packages/contiguity/__init__.py", line 4, in login

    return Contiguity(token, debug)

  File "/home/adminuser/venv/lib/python3.9/site-packages/contiguity/main.py", line 15, in __init__

    self.token = token.strip()

AttributeError: 'NoneType' object has no attribute 'strip'

2024-01-02 22:20:16.589 503 GET /script-health-check (10.12.7.28) 159.28ms

2024-01-02 22:20:21.375 Uncaught app exception

Traceback (most recent call last):

  File "/home/adminuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script

    exec(code, module.__dict__)

  File "/mount/src/project-xeroconvert/xeroconvert/app.py", line 9, in <module>

    from utils import *

  File "/mount/src/project-xeroconvert/xeroconvert/utils.py", line 21, in <module>

    client = contiguity.login(client_id, True)

  File "/home/adminuser/venv/lib/python3.9/site-packages/contiguity/__init__.py", line 4, in login

    return Contiguity(token, debug)

  File "/home/adminuser/venv/lib/python3.9/site-packages/contiguity/main.py", line 15, in __init__

    self.token = token.strip()

AttributeError: 'NoneType' object has no attribute 'strip'

2024-01-02 22:20:21.544 503 GET /script-health-check (10.12.7.28) 174.23ms
```

**Comment by janduplessis883** [comment]
![CleanShot 2024-01-02 at 22 34 54@2x](https://github.com/use-contiguity/python/assets/53879841/3336a956-5da3-4408-bfbf-1fc0f813f5a0)

**Comment by janduplessis883** [comment]
Seems to have resolved after rebooting streamlit.
